### ISSUE TITLE
Instability when training

### ISSUE THREAD

**Issue by conceptofmind** [vwxyzjn/a2c_is_a_special_case_of_ppo#2]
Hi,

Thank you for the great research.

I am working on implementing the findings from this paper in a different setting using TRLX. Unfortunately, when matching hyperparameters for A2C with PPO I seem to be experiencing instability with training and I am not able to match the results. 
![Screenshot from 2023-01-22 20-14-21](https://user-images.githubusercontent.com/25208228/213951282-ee3f8f2a-b346-4975-a1bc-c2848f3502f1.png)

Hyperparameters for trying to match A2C training:
```yml
train:
  seq_length: 1024
  epochs: 400
  total_steps: 10000
  batch_size: 5

  checkpoint_interval: 10000
  eval_interval: 100

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"  # A2C is a special case of PPO (https://arxiv.org/pdf/2205.09123.pdf)
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "lvwerra/gpt2-imdb"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "right"

optimizer:
  name: "rmsprop"
  kwargs:
    lr: 7.0e-4
    alpha: 0.99
    eps: 1.0e-5
    weight_decay: 0

scheduler:
  name: "linear"  # Ensure that the learning rate is constant
  kwargs:
    start_factor: 1
    total_iters: 0

method:
  name: "ppoconfig"
  num_rollouts: 5
  chunk_size: 5
  ppo_epochs: 1
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 1
  cliprange: 0.2
  cliprange_value: .inf
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    do_sample: True
```
Hyperparameters for original PPO training:
```yml
train:
  seq_length: 1024
  epochs: 100
  total_steps: 10000
  batch_size: 128

  checkpoint_interval: 10000
  eval_interval: 100

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "lvwerra/gpt2-imdb"
  num_layers_unfrozen: 2

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 128
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    do_sample: True
```
Any help would be greatly appreciated.

Thank you,

Enrico
